include ../Dev/as80.mk

UTILS_BIN = \
	    	c2backup.com  c2finder.com  c2man40.com  c2mini40.com  c2ramldr.com \
		c2cfgbck.com  c2idetst.com  c2man.com    c2mini.com    c2sram.com

all: $(UTILS_BIN)

clean:
	rm -f $(UTILS_BIN)

.PHONY: all clean
